# Site settings
title: Sufficient Grace
email: cellphone@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  With God's sufficient grace, I stand as a developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://grace0927.github.io" # the base hostname & protocol for your site
github_username:  grace0927

# Build settings
markdown: kramdown
